name: E2E Tests

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - coverage-e2e
      
jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install

    - name: Install nyc
      run: npm i nyc -g

    - name: Install http-server
      run: npm install -g http-server

    - name: Start http-server
      run: http-server -p 5501 &
      # The ampersand (&) runs http-server in the background

    - name: Run tests
      run: npm run test:e2e
    
    - name: Install lcov
      run: sudo apt-get install lcov
    
    - name: Generate lcov report
      run: nyc report --reporter=lcov
    
    - name: Filter report
      run: lcov --remove ./coverage/lcov.info '*/node_modules/*' '*/cdn.quilljs.com/*' '*/fonts.googleapis.com/*' --output-file coverage.info

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v6.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_ID}}
      with:
        coverageLocations: ${{ github.workspace }}coverage.info:lcov
        debug: true