name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Check_Jest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Dependencies
      run: npm install

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v6.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_ID}}
      with:
        coverageCommand: npm run test:unit
        coverageLocations: ${{ github.workspace }}/coverage/lcov.info:lcov
        debug: true
