name: JS Doc Generation
on:
  pull_request:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src/scripts
          output_dir: ./docs

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update JS Docs
          committer_name: GitHub Actions
          committer_email: actions@github.com
