name: Lighthouse CI
on:
  pull_request:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install && npm install -g @lhci/cli@0.13.x && npm install http-server
    - run: nohup npm run build &
    - run: sleep 5
    - run: lhci autorun
