name: Lighthouse CI
on:
  pull_request:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install npm
      run: npm install 

    - name: Install Lighthouse
      run: npm install -g @lhci/cli@0.13.x

    - name: Install http-server
      run: npm install -g http-server

    - name: Start Local Server
      run: http-server -p 8080 &

    - name: Wait for server to start
      run: sleep 5
      
    - name: Run Lighthouse
      run: lhci autorun
